<h2>Szczegóły oferty <?= $oferta->numer ?></h2>

<div class="row">
    <div class="col-lg-4">
            <h4>typ_oferty<br /></h4>
            <?= $this->oferta->typ_oferty ?><br />
            <h4>typ_nieruchomosci<br /></h4>
            <?= $this->oferta->typ_nieruchomosci ?><br />
            <h4>numer<br /></h4>
            <?= $this->oferta->numer ?><br />
            <h4>powierzchnia<br /></h4>
            <?= $this->oferta->powierzchnia ?><br />
            <h4>cena<br /></h4>
            <?= $this->oferta->cena ?><br />
    </div>
</div>